choco install vscode -y
choco install git -y
choco install python -y
choco install powershell -y
choco install chocolatey-autoupdater -y
choco install virtualbox -y
choco install nodejs -y
choco install docker -y
choco install jenkins -y
choco install aws-vault -y
choco install azure-cli -y
choco install vscode-ansible -y
